---
# tasks file for MicroJoe.prosody

- name: Install debian dependencies
  apt:
    name: apt-transport-https
    state: present

- name: Install official prosody repository's key
  apt_key:
    url: https://prosody.im/files/prosody-debian-packages.key
    state: present

- name: Install official prosody repository
  apt_repository:
    repo: deb https://packages.prosody.im/debian buster main
    state: present

- name: Install prosody package
  apt:
    name: prosody
    state: present
    update_cache: yes

- name: Configure prosody
  template:
    src: prosody.cfg.lua.j2
    dest: /etc/prosody/prosody.cfg.lua
    group: prosody
    owner: root
    mode: 0640
    validate: "luac -p %s"
  notify: reload prosody config

- name: Copy cert hook script
  template:
    src: copy-prosody-cert.sh.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/copy-prosody-cert.sh
    group: prosody
    owner: root
    mode: 0750

- name: Enable and restart prosody service
  service: name=prosody enabled=yes state=restarted
